"""Apply exact, reviewable HEP-reader wording edits to the existing manuscript."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
p = ROOT / "main.tex"
s = p.read_text(encoding="utf-8")

edits = [
    ("Longitudinal Gaps and Readout Connectivity in a Pilot", "Longitudinal Gaps and Spatial Hit Connectivity in a Pilot"),
    ("We test whether agreement in mean energy and occupancy implies agreement in shower structure for a hierarchical neutron generator in an ePIC Zero-Degree Calorimeter simulation. The target is raw deposited energy in 6,790 stored readout channels, without digitization or an analysis threshold. One checkpoint trained on 26,624 showers is compared with Geant4 at 10,000 matched incident conditions spanning 50--250\\,GeV kinetic energy. Among nonempty showers, the generated sample has 0.25 more active layers on average, but its last active layer lies 4.42 layers farther downstream and its occupied span contains 3.95 more inactive layers. The mean graph-component count rises from 23.42 to 59.39. Bounding the difference in occupied-layer run counts leaves an excess of at least 30.45 components within runs, or 84.6\\% of the observed 35.97-component increase. Thus empty-layer separations alone do not account for the graph fragmentation. The high-level classifier AUROC of 0.775 exceeds the recorded screening maximum of 0.65. These aggregate-only results concern one training seed and a repeatedly inspected validation sample. Physical segmentation, threshold sensitivity and variation across fits remain unverified; the comparison does not establish calibrated detector performance.",
     "We test whether similar mean deposited energy and active-channel counts imply similar shower structure for a hierarchical neutron generator in an ePIC Zero-Degree Calorimeter simulation. The target is raw energy in 6,790 stored channels: every positive deposit counts as active, without digitization or an analysis threshold. One model checkpoint trained on 26,624 showers is compared with Geant4 at 10,000 matched incident conditions spanning 50--250\\,GeV kinetic energy. Among nonempty showers, the mean active-layer count differs by 0.25, yet the last layer with a deposit lies 4.42 layers farther downstream and the occupied span contains 3.95 more skipped layers. The mean number of connected hit groups on the model graph rises from 23.42 to 59.39. After allowing for empty layers that split the hit pattern into contiguous active-layer segments, at least 30.45 of the 35.97 excess groups (84.6\\%) remain within those segments. The high-level classifier AUROC of 0.775 exceeds the recorded screening criterion of 0.65; its condition-only control failed. These aggregate results use one training seed and a repeatedly inspected validation sample. Threshold dependence, detector segmentation, repeated fits and reconstruction effects remain unmeasured."),
    ("A surrogate for detailed particle transport must therefore reproduce spatial organization as well as total energy. Here, support is the set of stored channels with positive deposit; occupancy counts its members.",
     "A surrogate for detailed particle transport must therefore reproduce hit positions and correlations as well as total energy: altered hit patterns could change clustering and reconstructed energy or angle. Here the hit pattern (mathematical support) is the set of stored channels with positive deposited energy; its size is the active-channel count. These are simulation deposits, not digitized detector hits."),
    ("The graph components below diagnose spatial structure; this study does not measure their effect on reconstruction. We ask whether similar raw-deposit and occupancy means also imply similar longitudinal organization. Here, they coexist with deeper deposits and more inactive layers in the occupied span. We derive an aggregate bound showing that most of the component-count excess remains within occupied-layer runs.",
     "The graph-connected hit groups below diagnose spatial structure; their effect on reconstruction is not measured here. We ask whether similar mean raw deposits and active-channel counts also imply similar longitudinal organization. Here, they coexist with a later last deposit and more skipped layers between the first and last deposits. An aggregate bound shows that most of the extra graph-connected groups remain after accounting for separation by empty layers."),
    ("For $E\\geq m_n$, the two energy features carry the same physical information because $E=\\Kinc+m_n$; both are inputs to this checkpoint. Direction features vanish at zero momentum, and the clamp is numerical.",
     "For $E\\geq m_n$, the two energy features carry the same physical information because $E=\\Kinc+m_n$; retaining both documents this checkpoint's input convention rather than two independent measurements. Direction features vanish at zero momentum, and the clamp is numerical."),
    ("No analysis threshold or additional time selection is applied; the production integration window is unknown. We call an event with zero total readout deposit an empty shower.",
     "Every strictly positive stored deposit enters the hit pattern; no MIP-scale threshold or additional time cut is applied, and the production integration window is unknown. Tiny deposits can therefore affect hit counts, gaps and graph connectivity. We call an event with zero total stored deposit an empty shower; this observation alone does not identify non-interaction, escape or any other cause."),
    ("The production geometry tag, materials, transport settings and coordinate origin are undocumented; layer indices are not interaction lengths.",
     "The production geometry tag, materials, transport settings and coordinate origin are undocumented. Without verified absorber composition and thickness, a layer index cannot be converted to radiation lengths $X_0$ or nuclear interaction lengths $\\lambda_I$."),
    ("with coordinate guide $x=-0.025z$ (unequal axis scales). Center/right: ECAL/HCAL faces, colored by positions per ID. The guide does not establish the beam axis; ID multiplicity does not establish electronic ganging.",
     "with a guide of $x/z=-0.025$, a 25-mrad slope comparable to the nominal EIC crossing angle (unequal axis scales). Center/right: ECAL/HCAL faces, colored by positions per ID. The stored coordinate frame does not establish beam-axis alignment; ID multiplicity does not establish electronic ganging."),
    ("The generator and connectivity diagnostic share this graph, which represents adjacency through readout-centroid distances.",
     "This is a three-dimensional nearest-centroid graph: eight lateral neighbors per channel and four forward neighbors in the next layer. The generator passes messages on these links, and the diagnostic groups positive-deposit channels connected by them. Graph neighbors are not independently verified physical tile neighbors."),
    ("Per-event masks and energies were not included in that summary; exact run counts, paired structural intervals and threshold studies require a new event-level evaluation of the project checkpoint.",
     "The publicly released summary lacks per-event masks and energies; exact contiguous-segment counts, paired structural intervals and threshold studies require another event-level evaluation with the collaboration-owned events and checkpoint."),
    ("The generator builds a shower at three levels of stored readout: event response, longitudinal allocation, and channel deposits", "The generator builds a stored shower readout in physical order: total deposit, longitudinal layer pattern and energy, then channel positions and deposits"),
    ("The response stage separates zero from nonzero stored response (a hurdle model), then describes fluctuations in its magnitude. Here visibility means nonzero deposited energy, not optical visibility or the probability of an inelastic interaction.",
     "The two-part response stage first samples whether total stored energy is zero, then samples the magnitude when positive. We call the positive-deposit indicator visibility; it describes the stored readout, not whether a neutron underwent an inelastic interaction."),
    ("$F$ marks the first stored deposit, not necessarily the first inelastic interaction. The mask $\\mathbf A$ specifies occupied depth and gaps; its factorization omits residual co-activation at fixed $(h_c,T,F)$.",
     "$F$ marks the first stored deposit, not necessarily the first inelastic interaction. The mask $\\mathbf A$ specifies which layers contain any positive deposit. At fixed $(h_c,T,F)$, Eq.~\\eqref{eq:activity} samples later layers independently: an intermediate layer can be empty even when deposits occur on both sides. Physical cascades correlate deposits across depth, but whether this assumption causes the observed gaps requires a controlled test."),
    ("Gumbel-top-$K$ samples $K_\\ell$ distinct channels without replacement. Selecting the top $K_\\ell$ enforces the requested count exactly, but imposes no adjacency or connectivity constraint.",
     "Gumbel-top-$K$ samples $K_\\ell$ distinct channels without replacement. Selecting the top $K_\\ell$ enforces the requested count exactly, but imposes no adjacency or connectivity constraint: isolated positive-deposit channels remain possible despite graph-informed scores."),
    ("Each training component receives reference-derived targets and upstream values (teacher forcing). During generation, it receives their sampled values, allowing errors to propagate through the cascade. We therefore evaluate complete generated showers (free-running generation)",
     "During training, each stage receives reference-derived upstream values (teacher forcing); when generating a full shower, it receives the preceding stages' sampled values. Errors can therefore propagate through the cascade. We evaluate those complete generated showers"),
    ("We examine the generated readout at three scales: total and section deposits, longitudinal layer structure, and channel-level support.",
     "We examine the generated readout at three scales: total and ECAL/HCAL deposits, the depth pattern of active layers, and the positive-deposit channel pattern."),
    ("Support measurements use a strictly positive energy definition; no detector or analysis threshold is applied. For a nonempty shower, let $F$ and $L$ be the first and last active layers, and $A_\\ell$ the activity indicator. The occupied span is $L-F+1$ and the number of inactive layers within it is",
     "Hit-pattern measurements count every strictly positive stored deposit, with no detector or analysis threshold. For a nonempty shower, let $F$ and $L$ be the first and last layers containing a deposit, and $A_\\ell$ their activity indicator. The occupied span is $L-F+1$; the number of skipped layers inside it is"),
    ("This counts inactive layers, not contiguous runs. An interior gap occurs when $G>0$. We also count active channels and weakly connected components $C_1,\\ldots,C_m$ of their induced subgraph, ignoring edge direction, and report the largest-component fraction $\\max_j|C_j|/|S|$ for occupied set $S$. A component is a group of occupied channels joined by paths using only occupied channels. These support metrics condition on nonempty readout, leaving 9,907 reference and 9,858 generated showers.",
     "The longitudinal gap count $G$ counts skipped layers, not separate gap regions; an interior gap occurs when $G>0$. We also count active channels and graph-connected hit groups: the weakly connected components $C_1,\\ldots,C_m$ of the positive-deposit subgraph, ignoring edge direction. For the active-channel set $S$, we report the fraction $\\max_j|C_j|/|S|$ in its largest group. Channels belong to one group if occupied-channel paths connect them on this fixed graph. These are zero-threshold graph groups, not reconstructed topological clusters. The hit-pattern metrics condition on nonempty readout, leaving 9,907 reference and 9,858 generated showers."),
    ("The component count depends on longitudinal activity even if within-layer support were unchanged. Graph edges join only the same or adjacent layers. If $R$ is the number of maximal runs of occupied layers, then $m\\geq R$: an empty layer between two occupied runs blocks every path between them. Consecutive empty layers constitute one separation, so $G$ alone specifies neither $R$ nor lateral fragmentation.",
     "The connected-group count changes when longitudinal gaps split a hit pattern, even if within-layer hits are unchanged. Graph edges join only the same or adjacent layers. Let $R$ count contiguous active-layer segments: each is a maximal block of consecutive layers containing a deposit. An empty layer between two segments blocks every path, so $m\\geq R$. Consecutive empty layers constitute one separation; thus $G$ alone does not determine $R$ or within-segment disconnection."),
    ("Define $Q=m-R$, the component count beyond one per occupied-layer run (Fig.~\\ref{fig:support}).", "Define $Q=m-R$, the number of graph-connected groups beyond one per contiguous active-layer segment (Fig.~\\ref{fig:support}). If each segment formed one connected group, $Q=0$; $Q>0$ means at least one segment contains disconnected groups, either laterally or across adjacent layers."),
    ("This deterministic aggregate bound is not a confidence interval or causal decomposition. With event activity masks, $R$ and $Q$ could be computed exactly; the aggregate report does not retain them. Components characterize graph-defined support, not detector-reconstruction clusters",
     "This deterministic aggregate bound is not a confidence interval or causal decomposition. With event activity masks, $R$ and $Q$ could be computed exactly; the aggregate report does not retain them. The bound removes the maximum explanation from empty-layer separations; it does not isolate transverse splitting. These graph-connected groups are not detector-reconstruction clusters"),
    ("Members of a matched condition pair can enter opposite partitions; its condition-only AUROC of 0.464 is a failed control consistent with opposite-label twin bias.",
     "Members of a matched condition pair can enter opposite partitions: one generated and one Geant4 shower share the same incident four-vector. This pair splitting can make condition memorization useful for predicting the opposite label in the held-out fold. The condition-only AUROC of 0.464 is a failed control consistent with this bias; its precise cause is unverified."),
    ("The similar total means conceal opposing section-level shifts: generated ECAL deposit is higher by 0.175\\,GeV (8.3\\%) and HCAL deposit lower by 0.129\\,GeV (5.8\\%)",
     "The similar unweighted totals conceal opposite ECAL and HCAL shifts: generated ECAL deposit is higher by 0.175\\,GeV (8.3\\%) and HCAL deposit lower by 0.129\\,GeV (5.8\\%). These shifts could matter after section-specific calibration, which this study does not evaluate"),
    ("The generated showers have nearly the same mean number of active layers as the reference (54.83 versus 54.58), but the occupied layers lie farther downstream.",
     "The generated showers have nearly the same mean number of active layers as the reference (54.83 versus 54.58), but their last positive deposit lies farther downstream. This is an extended zero-threshold footprint, not a measured change in physical shower termination."),
    ("The fraction of nonempty showers with an interior gap rises from 52.43\\% to 93.53\\%", "The fraction of nonempty showers with at least one skipped layer rises from 52.43\\% to 93.53\\%"),
    ("gap count $G$ and occupied runs $R$. Right: all four layers are active ($R=1$), but occupied channels form three components ($m=3$), so $Q=m-R=2$.",
     "gap count $G$ and contiguous active-layer segments $R$. Right: all four layers are active ($R=1$), but occupied channels form three graph-connected groups ($m=3$), so $Q=m-R=2$."),
    ("Generated showers have 28.7 fewer active channels on average, but 35.97 more weak components on the model graph.",
     "Generated showers have 28.7 fewer positive-deposit channels on average, but 35.97 more graph-connected hit groups on the model graph."),
    ("The bound in Sec.~\\ref{sec:diagnostics} places the mean within-run excess between 30.45 and 37.14 components; at least 84.6\\% of the component increase cannot be explained by additional runs.",
     "The bound in Sec.~\\ref{sec:diagnostics} places the mean extra groups within contiguous active-layer segments between 30.45 and 37.14; at least 84.6\\% of the total group-count increase cannot be explained by additional empty-layer separations. It does not identify the energy carried by those groups or how a thresholded clusterer would merge them."),
    ("Its high-level score exceeds the recorded screening maximum of 0.65.",
     "Its high-level score exceeds the recorded development-screening criterion of 0.65, whose pre-analysis status is not independently established."),
    ("Graph connectivity distinguishes more than empty-layer separations.",
     "The connected hit pattern differs beyond the separations forced by empty layers."),
    ("This establishes a within-run graph-fragmentation discrepancy in these samples. It does not identify a purely lateral effect",
     "This establishes excess graph disconnection within contiguous active-layer segments in these samples. It does not identify a purely lateral effect"),
    ("Strict-positive support is a property of stored simulation deposits, not electronics readout. Soft or late deposits can change gaps and components; their contribution cannot be quantified without channel-energy spectra and time information.",
     "The strict $E>0$ hit pattern describes stored simulation deposits, not electronics readout. Even very small or late deposits can change the skipped-layer and connected-group counts; their actual contribution is unknown without channel-energy spectra and timing information. Threshold and timing scans are therefore necessary before interpreting the result as a reconstructed clustering defect."),
    ("At least 30.45 of the 35.97 excess components remain within occupied-layer runs. Empty-layer separations are therefore insufficient to explain fragmentation on this graph.",
     "At least 30.45 of the 35.97 extra graph-connected groups remain after accounting for contiguous active-layer segments. Empty-layer separations are therefore insufficient to explain the difference on this graph."),
    ("With this class-stratified 70/30 split, 42\\% of pairs straddle partitions in expectation; a scored row has a 70\\% chance of its opposite-label twin entering the fitting partition (about 4,200 scoring rows). This can bias condition-sensitive scores downward.",
     "With this class-stratified 70/30 split, 42\\% of pairs straddle partitions in expectation; a scored row has a 70\\% chance of its opposite-label, identically conditioned partner entering the fitting partition (about 4,200 scoring rows). This can bias condition-sensitive scores downward; it does not establish the numerical cause of the observed AUROC."),
]

for old, new in edits:
    count = s.count(old)
    if count != (2 if old == "Longitudinal Gaps and Readout Connectivity in a Pilot" else 1):
        raise AssertionError((count, old[:100]))
    s = s.replace(old, new)

p.write_text(s, encoding="utf-8")
print(f"Applied {len(edits)} exact prose replacements; equations and numerical tables untouched")
