import re,json,shutil,hashlib
from session import ROOT,HERE,record,sha

sources=[
 {'source':'APS Style Basics','url':'https://journals.aps.org/authors/style-basics','reading':'Titles and Abstracts','finding':'Titles should identify the subject without promotional wording. Abstracts must stand alone and avoid unexplained abbreviations.','application':'Name neutron showers in the title; state the target and comparison immediately; spell out the classifier metric.'},
 {'source':'IOP Article Structure','url':'https://publishingsupport.iopscience.iop.org/questions/structure-and-format-of-your-journal-article/','reading':'Abstract, Discussion, Conclusion','finding':'Summarize method, principal results and implications; the discussion interprets results in context and the conclusion identifies the contribution and follow-up. General guidance suggests an abstract no longer than 300 words.','application':'Use a sub-300-word abstract; open the discussion with the meaning of the discrepancy; end with a bounded validation lesson. This is guidance, not a claimed target-journal requirement.'},
 {'source':'Evaluating generative models in high energy physics','url':'https://arxiv.org/html/2211.10295','reading':'Abstract; sections IV-VI','finding':'Different metrics have different sensitivities; an interpretable observable and a multivariate score provide complementary evidence.','application':'Connect the observed differences to complementary validation observables; do not turn agreement in a mean or a failed-control classifier score into fidelity.'},
 {'source':'ePIC SiPM-on-tile ZDC design','url':'https://arxiv.org/html/2406.12877v2','reading':'Abstract; design; performance; summary','finding':'The detector study evaluates reconstructed neutron energy and angle using hit energies and positions. It explicitly separates demonstrated performance from prospective timing work.','application':'Name neutron energy and angle as the downstream questions, while stating that the present graph counts do not measure either and the production geometry is not verified equivalent.'},
 {'source':'CaloDREAM','url':'https://arxiv.org/html/2405.09629v3','reading':'Abstract; classifier discussion; section 5 Outlook','finding':'Low-energy deposits, sparsity and thresholds can affect comparisons. Generalization to irregular geometry, hadrons and varying angles requires further study.','application':'Keep the zero-threshold definition adjacent to the findings; preserve unmeasured threshold/graph sensitivity and numerical-solver limits.'},
 {'source':'ALICE normalizing-flow/co-activation study','url':'https://arxiv.org/html/2608.12795','reading':'Abstract; conditional/co-activation results; bootstrap discussion','finding':'The study uses conditional response and co-activation observables with explicit resampling units and uncertainty limitations.','application':'State the reused validation bank, separate nonempty samples and absence of paired structural intervals; distinguish descriptive differences from a significance or causal claim.'}
]
record('Primary research completed',{'sources':sources,'assessment':'Literature supports the editorial criteria, not this checkpoint\'s numerical results. All numbers remain bound to local aggregate evidence.','limitations':'No external HEP reader was polled. Clarity assessment is research-informed editorial QC, not independent peer review.'})
(HERE/'research.json').write_text(json.dumps(sources,indent=2)+'\n',encoding='utf-8')
(HERE/'research.md').write_text('# HEP audience research\n\n'+ '\n\n'.join('## '+s['source']+'\n\n['+s['reading']+']('+s['url']+'). '+s['finding']+'\n\nApplication: '+s['application'] for s in sources)+'\n',encoding='utf-8')
backup=HERE/'before';backup.mkdir(exist_ok=False)
for name in ['main.tex','references.bib','CITATION.cff','README.md','STATUS.md','audit/finalization_20260930.json','audit/finalization_20260930.md','audit/final_build_audit.json','audit/visual_review_finalization_20260930.json','audit/arxiv_package_20260930.json','output/fast_mc_zdc_manuscript.pdf','output/fast_mc_zdc_submission_source.zip']:
    shutil.copy2(ROOT/name,backup/(ROOT/name).name)

title='Longitudinal Gaps and Spatial Hit Connectivity in Generated Neutron Showers: A Pilot Zero-Degree Calorimeter Study'
oldtitle='Longitudinal Gaps and Spatial Hit Connectivity in a Pilot Generative Model of Zero-Degree Calorimeter Showers'
abstract=r'''We compare the longitudinal hit pattern and spatial connectivity of single-neutron showers from a pilot flow-matching generator with Geant4 in an ePIC zero-degree calorimeter simulation. The model was trained on 26,624 showers and evaluated at 10,000 matched incident-neutron conditions spanning 50--250\,GeV kinetic energy. The target is raw deposited energy in 6,790 stored channels, with every positive deposit counted as a hit and no digitization or analysis threshold. The all-event mean deposit differs by 1.0\%. Among nonempty showers, the mean active-layer count differs by 0.25 (54.83 generated versus 54.58 Geant4, of 65 layers), yet the generated last active layer lies 4.42 layers farther downstream and the occupied span contains 3.95 more empty layers. Connected hit groups join positive-deposit channels on the fixed nearest-centroid graph; they are not reconstructed clusters. Their mean number is 23.42 for Geant4 and 59.39 for the generator. After allowing one group per contiguous active-layer segment, at least 30.45 of the 35.97 excess groups (84.6\%) remain: empty layers alone cannot explain the graph discrepancy. A classifier using shower summaries gives an area under the receiver operating characteristic curve of 0.775, but its control using incident conditions alone gives 0.464 rather than the chance value 0.5, preventing a calibrated fidelity interpretation. These aggregate results use one training seed and a repeatedly inspected validation sample. They identify a spatial discrepancy missed by selected global means; structural uncertainties, threshold and graph sensitivity, and reconstruction effects remain unmeasured.'''

discussion=r'''\section{Discussion}
\label{sec:discussion}

\subsection{Interpretation and diagnostic tests}

The main observation is a mismatch in where positive deposits occur, even when selected global means are close. The generated showers reach farther downstream and contain more interior empty layers and disconnected hit groups. Their mean energy-weighted depth remains nearly unchanged, so the last active layer should not be interpreted as an energy centroid or a reconstructed shower length. The comparison illustrates why calorimeter validation needs complementary energy and shape observables~\cite{calochallenge,kansalmetrics}.

The component bound makes the graph result more specific. Allowing one connected group per contiguous active-layer segment leaves at least 30.45 of the 35.97 excess groups (84.6\%) within those segments (Sec.~\ref{sec:diagnostics}). This establishes excess graph disconnection within contiguous active-layer segments. It need not be purely lateral: adjacent occupied layers may fail to connect. The bound is an algebraic statement about the separate nonempty samples, which need not share conditions; it is neither a significance estimate nor evidence for a particular failure mechanism. It concerns stored-ID connectivity on the model graph, not fragmentation into reconstructed calorimeter clusters.

Equation~\eqref{eq:activity} assumes conditional independence of later-layer activity given $(h_c,T,F)$: once the incident kinematics, sampled total deposit and first active layer are fixed, later layers are drawn independently. In a three-layer example, fix $F=0$ and let layers 1 and 2 be both active with probability $p$ and both inactive otherwise. Independent draws with the same marginals preserve the mean active-layer count but give an interior-gap probability $p(1-p)$ instead of zero and increase the mean last layer by $p(1-p)$. This explains a possible signature, not the measured magnitude. Sampled $T$ and $F$ can still induce dependence when their values vary; the first deposited layer is not necessarily the first inelastic-interaction depth.

A direct test builds a null sample from Geant4 itself: redraw each later layer's activity independently, with probabilities matched in energy, direction, $T$ and $F$, and check whether the depth and gap shifts appear. A complementary test runs the generator with the Geant4 activity mask substituted for its own; substituting only the reference $T$ and $F$ would leave the factorization intact. L2LFlows and iCaloFlow model interlayer dependence~\cite{l2lflows,icaloflow} and motivate a matched comparison.

The channel-placement stage offers a second hypothesis. Scores trained with binary cross entropy are not automatically calibrated probabilities for a channel to be selected after fixed-count Gumbel sampling. Independent perturbations can separate selected channels even when the scores vary smoothly in space. Comparing channel inclusion frequencies at fixed layer and count, followed by a placement model matched to those frequencies, would test whether the discrepancy lies in occupancy or its spatial correlations. The channel flow cannot repair the selected hit pattern in exact arithmetic. Shared upstream random states and cross-layer attention can nevertheless correlate shower centroids without a common event latent; measuring those correlations would test shower-axis coherence.

\subsection{Limitations and robustness}

Paired sampling intervals for the headline structural means are not retained. Large descriptive differences do not establish robustness across training seeds, thresholds or graphs. A three-seed study and full-data fit are needed to separate architecture effects from training-population and optimization effects. The failed condition-only classifier control is a separate limitation: the quoted classifier scores cannot supply the missing structural significance. A rerun that keeps each matched pair in one partition is needed on the same validation bank.

The zero-threshold hit pattern describes stored simulation deposits, not electronics readout. Tiny or late deposits may change skipped-layer and connected-group counts; their contribution is unknown without channel-energy and timing data. Thresholding might remove a low-energy downstream tail or create new interior gaps; neither effect is measured. Threshold and timing scans are therefore necessary, together with an independently defined physical-neighbor graph, before interpreting this as a reconstruction defect. The cited design uses a 0.5\,MeV MIP scale, a reconstructed-hit cut above 0.5 MIP and $t<275$\,ns~\cite{epiczdc}; these are design-study choices, not verified settings of the analyzed production. These motivate a 0.25\,MeV HCAL sensitivity scan, but transferring the cuts requires the production segmentation and timing convention; a reference-only time cut would compare different targets.

The model has no explicit impact-position input. The recorded fixed gun vertex makes direction informative about the nominal entry point, but the production surface and event-level positions are not available here. Position-conditioned residuals and the joint empty-shower contingency table would test geometric acceptance; marginal empty fractions alone cannot answer this.

Response-tail studies require counts of generated draws clipped by the cap and reference deposits above it. Numerical sensitivity requires a solver-step study. A locked bank with verified identities and repeated generation at fixed conditions is also needed. These tests would distinguish sensitivity to numerical choices from a reproducible mismatch in the generated distributions.

\subsection{Timing and detector applications}

For a neutron calorimeter, the downstream questions concern reconstructed energy and direction. The cited ePIC design evaluates both using hit energies and positions~\cite{epiczdc}; the present stored-ID graph counts measure neither. Relating this raw-deposit study to detector performance requires production metadata, training-only calibration applied unchanged to both samples, and energy and position reconstruction. The ECAL and HCAL shifts cancel only in the unweighted stored-energy sum. A sampling fraction from another production cannot establish this model's calibrated bias. Once the production geometry and readout definition are verified, applying the same reconstruction to both samples would test whether the observed hit-pattern differences affect neutron measurements.

The evaluation took 3,442\,s for 10,000 pairs. Its nonoverlapping timed analysis stages total 1,009\,s, leaving 2,433\,s (0.243\,s per matched condition) for generation, I/O and other untimed work; generation latency was not isolated. A matched end-to-end benchmark must include both solvers, decoding and output handling, with hardware and batch size specified for generator and Geant4. The present timing therefore establishes no acceleration factor.

% Allow natural page flow.
'''
conclusion=r'''This pilot study of 50--250\,GeV single-neutron showers shows that similar mean deposited energy, active-layer count and active-channel count do not imply matched longitudinal or graph structure. A difference of 0.25 active layers coexists with a last active layer shifted by 4.42 layers and 3.95 additional empty layers in the occupied span. At least 30.45 of the 35.97 extra graph-connected groups remain after accounting for contiguous active-layer segments. Empty-layer separations are therefore insufficient to explain the difference on this graph.

The result supports checking longitudinal occupancy and hit connectivity alongside energy response when evaluating a shower generator. It is a descriptive finding for one training seed on a reused validation bank, not a demonstrated loss of reconstructed neutron performance. Paired structural uncertainties, repeated fits, controlled activity and channel-placement tests, and threshold and graph sensitivity are needed to establish robustness and origin. Applying a common reconstruction after verifying the production geometry would then determine the relevance for neutron energy and direction.'''

p=ROOT/'main.tex';before=p.read_text(encoding='utf-8');after=before
assert oldtitle in after
after=after.replace(oldtitle,title)
old_tex_title=re.search(r'\\title\{[^\n]+',after).group()
after=after.replace(old_tex_title,r'\title{Longitudinal Gaps and Spatial Hit Connectivity in Generated\\Neutron Showers: A Pilot Zero-Degree Calorimeter Study}')
after=re.sub(r'(?s)(\\begin\{abstract\}\n).*?(\n\\end\{abstract\})',lambda m:m[1]+abstract+m[2],after)
start=after.index(r'\section{Discussion}');end=after.index(r'\section{Conclusion}',start)
after=after[:start]+discussion+after[end:]
start=after.index(r'\section{Conclusion}')+len(r'\section{Conclusion}')
end=after.index(r'\section*{Code and data availability}',start)
after=after[:start]+'\n\n'+conclusion+'\n\n'+after[end:]
for env in ['equation','tabular']:
    pattern=r'\\begin\{'+env+r'\}.*?\\end\{'+env+r'\}'
    assert re.findall(pattern,before,re.S)==re.findall(pattern,after,re.S),env
assert len(abstract.split())<300,len(abstract.split())
p.write_text(after,encoding='utf-8')
for name in ['CITATION.cff','README.md']:
    p=ROOT/name;s=p.read_text(encoding='utf-8');assert oldtitle in s;s=s.replace(oldtitle,title);p.write_text(s,encoding='utf-8')
note='\n## HEP framing research and review, 2 October 2026\n\nThe title now names generated neutron showers. The abstract states the target, model comparison, principal quantitative finding and evidentiary limits without an unexplained classifier acronym. The discussion distinguishes the observed discrepancy, possible causes, required tests and relevance to neutron reconstruction; the conclusion states the validation lesson and its one-seed scope. APS/IOP guidance and four relevant primary research papers inform the revision. All 14 numbered equations, four numerical tables, figures and evidence remain unchanged. Research, decisions and full QA are recorded in `audit/hep_framing_research_20261002/`. This is an editorial revision of v0.22.1, not new physics validation.\n'
for name in ['README.md','STATUS.md']:
    with (ROOT/name).open('a',encoding='utf-8') as f:f.write(note)
pointer=ROOT/'audit/finalization_20260930.json';d=json.loads(pointer.read_text(encoding='utf-8'))
d['current_main_tex_sha256']=sha(ROOT/'main.tex')
d['hep_framing_research_20261002']={'status':'source_review_complete','record':'audit/hep_framing_research_20261002/events.json','previous_source_sha256':sha(backup/'main.tex'),'scope':'Research-informed title, abstract, discussion and conclusion review; numerical and equation/table preservation checked.'}
pointer.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8')
with pointer.with_suffix('.md').open('a',encoding='utf-8') as f:f.write('\nCurrent source pointer updated after HEP framing research and review. Prior source/audit preserved in `audit/hep_framing_research_20261002/before/`; see the research and events twins in that directory. Final full QA and visual review follow separately.\n')
record('Research-informed framing revision applied',{'title':title,'abstract_whitespace_words':len(abstract.split()),'changes':['Title identifies generated neutron showers and pilot ZDC scope.','Abstract starts with physics object and comparison, defines connected groups, spells out classifier metric and retains the failed control and exact pilot limitations.','Discussion begins with the meaning of the result, explains both hypotheses in detector-facing language, preserves counterexample and proposed controls, and names neutron reconstruction as untested.','Conclusion separates supported observation, validation lesson and remaining research.'],'preserved':['14 numbered equations','Four table bodies','All four figure definitions','All data and numerical reports','Author-requested disclosure','All guards and thresholds'],'current_main_tex_sha256':sha(ROOT/'main.tex'),'status':'Awaiting full build and rendered review.'})
print('Framing revision written; abstract words:',len(abstract.split()))
